version: '3.8'

services:
  master:
    container_name: "citus_master"
    image: "citusdata/citus:12.1.2"
    ports:
      - 5432:5432
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata-yellow:/var/lib/postgresql/data

  citus_worker:
    image: "citusdata/citus:12.1.2"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [citus_manager]
#    environment: *AUTH
    command: "/wait-for-manager.sh"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata-worker-yellow:/var/lib/postgresql/data
      - healthcheck-volume:/healthcheck

  citus_manager:
    container_name: "citus_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
#    environment: *AUTH

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  tarantool:
    container_name: mytarantool
    image: tarantool/tarantool:latest
    environment:
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "admin"
    ports:
      - 3301:3301

networks:
  pg-network:
    driver: bridge

volumes:
  pgdata-yellow:
  pgdata-worker-yellow:
  healthcheck-volume:
#  master1_data:
#  slave1_data:
#  slave2_data:
  rabbitmq_data: