version: '3.8'

services:
  master_main:
    container_name: "citus_master_main"
    image: "citusdata/citus:12.1.2"
    ports:
      - 5432:5432
    labels: ["com.citusdata.role=Master"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata-main:/var/lib/postgresql/data

  citus_worker_main:
    image: "citusdata/citus:12.1.2"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [citus_manager_main]
    command: "/wait-for-manager.sh"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata-worker-main:/var/lib/postgresql/data
      - healthcheck-volume:/healthcheck

  citus_manager_main:
    container_name: "citus_manager_main"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master_main]
##############################################################################################
  master_dialog:
    container_name: "citus_master_dialog"
    image: "citusdata/citus:12.1.2"
    ports:
      - 5433:5432
    labels: [ "com.citusdata.role=Master" ]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata-dialog:/var/lib/postgresql/data

  citus_worker_dialog:
      image: "citusdata/citus:12.1.2"
      labels: [ "com.citusdata.role=Worker" ]
      depends_on: [ citus_manager_dialog ]
      command: "/wait-for-manager.sh"
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
        - pgdata-worker-dialog:/var/lib/postgresql/data
        - healthcheck-volume:/healthcheck

  citus_manager_dialog:
      container_name: "citus_manager_dialog"
      image: "citusdata/membership-manager:0.3.0"
      volumes:
        - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
        - healthcheck-volume:/healthcheck
      depends_on: [ master_dialog ]





##############################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  tarantool:
    container_name: mytarantool
    image: tarantool/tarantool:latest
    environment:
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "admin"
    ports:
      - 3301:3301

networks:
  pg-network:
    driver: bridge

volumes:
  pgdata-main:
  pgdata-worker-main:
  pgdata-dialog:
  pgdata-worker-dialog:
  healthcheck-volume:
  rabbitmq_data: