spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    enabled: true
    placeholders:
      secret-key: secret-key
secret-key: secret-key
