spring:
  mvc:
    static-path-pattern: /public/**
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: pass
  flyway:
    baseline-on-migrate: true
    enabled: true
    placeholders:
      secret-key: secret-key
secret-key: secret-key

server:
  port: 8081