spring:
  mvc:
    static-path-pattern: /public/**
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://master1:5432/postgres
      username: postgres
      password: postgres
    slave:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://haproxy-pg:5432/postgres
      username: postgres
      password: postgres
flyway:
  datasources:               # Define Flyway configurations for each datasource
    master:                  # Targeting the 'master' datasource
      enabled: true          # Enable Flyway for the master datasource
      locations: classpath:db/migration  # Specify Flyway migration scripts location for master
      baseline-on-migrate: true  # Baseline on migrate for master datasource if needed
      placeholders:
        secret-key: ${secret-key}  # Define placeholders for master datasource migrations
    slave:                   # No Flyway configuration needed for 'slave' datasource
      enabled: false
secret-key: secret-key

server:
  port: 8081
base:
  url: arch.homework
  dialog-host: localhost
  counter-host: localhost
  dialog-port: 8081
  counter-port: 8082
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    prometheus:
      enabled: true